{
  "formatVersion": "1.1",
  "component": {
    "group": "ru.dreremin",
    "module": "logging-starter",
    "version": "1.10-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "logging-starter-1.10-SNAPSHOT.jar",
          "url": "logging-starter-1.10-SNAPSHOT.jar",
          "size": 23078,
          "sha512": "87affe33c871bdcdb877c5a3ff222361bbe0b43aca4c3ec2e8b54a9fa1a3652e50e62ebbc373ca5b837e10d1463f605f68e874c6e255f66ff34913670f6354f4",
          "sha256": "016a501495696ccacf3afd9630426c45a9b828ee043c32bd1d41a288d369113a",
          "sha1": "40dad07fba7969cfbc9841a2c6cacec9aea44414",
          "md5": "5605125338d8941b2dbff40c0c93323a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "3.2.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "3.2.5"
          }
        },
        {
          "group": "org.springframework.cloud",
          "module": "spring-cloud-starter-openfeign",
          "version": {
            "requires": "4.1.4"
          }
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.codehaus.janino",
          "module": "janino",
          "version": {
            "requires": "3.1.12"
          }
        }
      ],
      "files": [
        {
          "name": "logging-starter-1.10-SNAPSHOT.jar",
          "url": "logging-starter-1.10-SNAPSHOT.jar",
          "size": 23078,
          "sha512": "87affe33c871bdcdb877c5a3ff222361bbe0b43aca4c3ec2e8b54a9fa1a3652e50e62ebbc373ca5b837e10d1463f605f68e874c6e255f66ff34913670f6354f4",
          "sha256": "016a501495696ccacf3afd9630426c45a9b828ee043c32bd1d41a288d369113a",
          "sha1": "40dad07fba7969cfbc9841a2c6cacec9aea44414",
          "md5": "5605125338d8941b2dbff40c0c93323a"
        }
      ]
    }
  ]
}
