{
  "formatVersion": "1.1",
  "component": {
    "group": "ru.dreremin",
    "module": "logging-starter",
    "version": "1.11-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "logging-starter-1.11-SNAPSHOT.jar",
          "url": "logging-starter-1.11-SNAPSHOT.jar",
          "size": 23061,
          "sha512": "1394b20054af47ddbd10cda886289eddf0dbc61da4c1b4d38b964aea9131b0baf8fcaee5d65c24938b273a995f03dca63836413af2dd1bb2155596fbbdefefb5",
          "sha256": "3d912967858b9dec4126c44434b5fee526d45ea0fe0cda73b2a8c085937d510e",
          "sha1": "05da2065717408aeb1cb4e742c9b7eaa3c92cfda",
          "md5": "3253181ca296d15ee14a483aeb58aa44"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "3.2.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "3.2.5"
          }
        },
        {
          "group": "org.springframework.cloud",
          "module": "spring-cloud-starter-openfeign",
          "version": {
            "requires": "4.1.4"
          }
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.codehaus.janino",
          "module": "janino",
          "version": {
            "requires": "3.1.12"
          }
        }
      ],
      "files": [
        {
          "name": "logging-starter-1.11-SNAPSHOT.jar",
          "url": "logging-starter-1.11-SNAPSHOT.jar",
          "size": 23061,
          "sha512": "1394b20054af47ddbd10cda886289eddf0dbc61da4c1b4d38b964aea9131b0baf8fcaee5d65c24938b273a995f03dca63836413af2dd1bb2155596fbbdefefb5",
          "sha256": "3d912967858b9dec4126c44434b5fee526d45ea0fe0cda73b2a8c085937d510e",
          "sha1": "05da2065717408aeb1cb4e742c9b7eaa3c92cfda",
          "md5": "3253181ca296d15ee14a483aeb58aa44"
        }
      ]
    }
  ]
}
