{
  "formatVersion": "1.1",
  "component": {
    "group": "ru.dreremin",
    "module": "logging-starter",
    "version": "1.11-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "logging-starter-1.11-SNAPSHOT.jar",
          "url": "logging-starter-1.11-SNAPSHOT.jar",
          "size": 23115,
          "sha512": "a202640813fce91f04f50c6372e1aa602ac8d9f14472853b63085d1415d34ca62c69da962399fc1f887fbf542ee56fded9f1fc1c7a77c0db4acfb171e563dcbb",
          "sha256": "208af3388860f3c42bdc68457564debe4aef5020e3eb428b276d804e357eb564",
          "sha1": "4c837f5bc4833e30eb47ec631826044162318d36",
          "md5": "d138d0fea06bc4f71dce074140373850"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "3.2.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "3.2.5"
          }
        },
        {
          "group": "org.springframework.cloud",
          "module": "spring-cloud-starter-openfeign",
          "version": {
            "requires": "4.1.4"
          }
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.codehaus.janino",
          "module": "janino",
          "version": {
            "requires": "3.1.12"
          }
        }
      ],
      "files": [
        {
          "name": "logging-starter-1.11-SNAPSHOT.jar",
          "url": "logging-starter-1.11-SNAPSHOT.jar",
          "size": 23115,
          "sha512": "a202640813fce91f04f50c6372e1aa602ac8d9f14472853b63085d1415d34ca62c69da962399fc1f887fbf542ee56fded9f1fc1c7a77c0db4acfb171e563dcbb",
          "sha256": "208af3388860f3c42bdc68457564debe4aef5020e3eb428b276d804e357eb564",
          "sha1": "4c837f5bc4833e30eb47ec631826044162318d36",
          "md5": "d138d0fea06bc4f71dce074140373850"
        }
      ]
    }
  ]
}
