{
  "formatVersion": "1.1",
  "component": {
    "group": "ru.dreremin",
    "module": "logging-starter",
    "version": "1.7-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "logging-starter-1.7-SNAPSHOT.jar",
          "url": "logging-starter-1.7-SNAPSHOT.jar",
          "size": 15106,
          "sha512": "9356232fdf5e17d42a25e72d8cac0990f1d214309e84afd7fc492387c45bcded8cec9ce804dadccf99bb51b312c5c14a0d92dec8861610209706d096b653543e",
          "sha256": "8d84fa748462ff64294d8150c525081195ce186b6f5d32612c80ff39a0e355dc",
          "sha1": "3e38e2804baa5cf36ff08be8edc15e08c4959a54",
          "md5": "9c0fbc51cb13ed634843e566f8fbb551"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "3.2.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "3.2.5"
          }
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "logging-starter-1.7-SNAPSHOT.jar",
          "url": "logging-starter-1.7-SNAPSHOT.jar",
          "size": 15106,
          "sha512": "9356232fdf5e17d42a25e72d8cac0990f1d214309e84afd7fc492387c45bcded8cec9ce804dadccf99bb51b312c5c14a0d92dec8861610209706d096b653543e",
          "sha256": "8d84fa748462ff64294d8150c525081195ce186b6f5d32612c80ff39a0e355dc",
          "sha1": "3e38e2804baa5cf36ff08be8edc15e08c4959a54",
          "md5": "9c0fbc51cb13ed634843e566f8fbb551"
        }
      ]
    }
  ]
}
