{
  "formatVersion": "1.1",
  "component": {
    "group": "ru.dreremin",
    "module": "logging-starter",
    "version": "1.4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "logging-starter-1.4-SNAPSHOT.jar",
          "url": "logging-starter-1.4-SNAPSHOT.jar",
          "size": 13900,
          "sha512": "8b2bf1e28160a0b3970d158400f1b4bfe3d86f08b983680e5c94ce2a30be40bf62cf4683942867416eccce77947b154ea96e3dcb29d33489725821513f8ac54d",
          "sha256": "e3673da859a844cbd551a4be44128da37750ca9feb821379bbe2e1683ede8849",
          "sha1": "9a95c6f9eaa0c4d8bc3c6369eadecbb098f38484",
          "md5": "e50d6a315824af2ef38d03532c4c8dad"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "3.2.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "3.2.5"
          }
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "logging-starter-1.4-SNAPSHOT.jar",
          "url": "logging-starter-1.4-SNAPSHOT.jar",
          "size": 13900,
          "sha512": "8b2bf1e28160a0b3970d158400f1b4bfe3d86f08b983680e5c94ce2a30be40bf62cf4683942867416eccce77947b154ea96e3dcb29d33489725821513f8ac54d",
          "sha256": "e3673da859a844cbd551a4be44128da37750ca9feb821379bbe2e1683ede8849",
          "sha1": "9a95c6f9eaa0c4d8bc3c6369eadecbb098f38484",
          "md5": "e50d6a315824af2ef38d03532c4c8dad"
        }
      ]
    }
  ]
}
