{
  "formatVersion": "1.1",
  "component": {
    "group": "ru.dreremin",
    "module": "logging-starter",
    "version": "1.9-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "logging-starter-1.9-SNAPSHOT.jar",
          "url": "logging-starter-1.9-SNAPSHOT.jar",
          "size": 22069,
          "sha512": "dc7275009de9d27c1b5d7d958334e4080828dc481db375f5a6ecb5b52344f95d6d7aa6a0e73d5be9ebc5c4c53bf87dba9dcf403e15d40770124ce9631129eb7a",
          "sha256": "6f15748fb8b1bf0169b3daa05b4cea0b7a78bfa257c9c9c03a8822baeb75347c",
          "sha1": "ef6922ebeeb823859383cd5a3d64f80a9aa22653",
          "md5": "428709da7f3f9b9dc6088cf5498d1195"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "3.2.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "3.2.5"
          }
        },
        {
          "group": "org.springframework.cloud",
          "module": "spring-cloud-starter-openfeign",
          "version": {
            "requires": "4.1.4"
          }
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "logging-starter-1.9-SNAPSHOT.jar",
          "url": "logging-starter-1.9-SNAPSHOT.jar",
          "size": 22069,
          "sha512": "dc7275009de9d27c1b5d7d958334e4080828dc481db375f5a6ecb5b52344f95d6d7aa6a0e73d5be9ebc5c4c53bf87dba9dcf403e15d40770124ce9631129eb7a",
          "sha256": "6f15748fb8b1bf0169b3daa05b4cea0b7a78bfa257c9c9c03a8822baeb75347c",
          "sha1": "ef6922ebeeb823859383cd5a3d64f80a9aa22653",
          "md5": "428709da7f3f9b9dc6088cf5498d1195"
        }
      ]
    }
  ]
}
