{
  "formatVersion": "1.1",
  "component": {
    "group": "ru.dreremin",
    "module": "logging-starter",
    "version": "1.5-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "logging-starter-1.5-SNAPSHOT.jar",
          "url": "logging-starter-1.5-SNAPSHOT.jar",
          "size": 14357,
          "sha512": "5f0cca7889305cc3b92fe5f6c067d62065c755735d12ec8fdd21462661d6a65f745b3d85eec854224b589a8b510825d66ef9ef6063bd487a071825f91e987ffc",
          "sha256": "8e78ae37f2c43168fd545dab92e9968ab738c1b7de30eca18cc0315583eb16b5",
          "sha1": "a1cfd97a25e0d5b280ad6fbe4a6a3c53d54966fa",
          "md5": "25eae768b4cab821b85b1880f8c37255"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "3.2.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "3.2.5"
          }
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "logging-starter-1.5-SNAPSHOT.jar",
          "url": "logging-starter-1.5-SNAPSHOT.jar",
          "size": 14357,
          "sha512": "5f0cca7889305cc3b92fe5f6c067d62065c755735d12ec8fdd21462661d6a65f745b3d85eec854224b589a8b510825d66ef9ef6063bd487a071825f91e987ffc",
          "sha256": "8e78ae37f2c43168fd545dab92e9968ab738c1b7de30eca18cc0315583eb16b5",
          "sha1": "a1cfd97a25e0d5b280ad6fbe4a6a3c53d54966fa",
          "md5": "25eae768b4cab821b85b1880f8c37255"
        }
      ]
    }
  ]
}
