{
  "formatVersion": "1.1",
  "component": {
    "group": "ru.dreremin",
    "module": "logging-starter",
    "version": "1.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "logging-starter-1.8-SNAPSHOT.jar",
          "url": "logging-starter-1.8-SNAPSHOT.jar",
          "size": 22001,
          "sha512": "8812de5287e10c84ab47d7e28b428f178d6fa4b65c210f5e5fea0c4b207f10b58c8ce94db0e4ee1a4c14d57bcde853495316e92cc0363eb6812034c669da78e5",
          "sha256": "8d4b75e5f007abe789e82dd0155aa4bf311c1aed597ebfadfc802c21bce67dda",
          "sha1": "77066b57f86f3e5abd8aa59832d81afbdce7a8e7",
          "md5": "50836073606f20ec5219b72896caa53e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "3.2.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "3.2.5"
          }
        },
        {
          "group": "org.springframework.cloud",
          "module": "spring-cloud-starter-openfeign",
          "version": {
            "requires": "4.1.4"
          }
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "logging-starter-1.8-SNAPSHOT.jar",
          "url": "logging-starter-1.8-SNAPSHOT.jar",
          "size": 22001,
          "sha512": "8812de5287e10c84ab47d7e28b428f178d6fa4b65c210f5e5fea0c4b207f10b58c8ce94db0e4ee1a4c14d57bcde853495316e92cc0363eb6812034c669da78e5",
          "sha256": "8d4b75e5f007abe789e82dd0155aa4bf311c1aed597ebfadfc802c21bce67dda",
          "sha1": "77066b57f86f3e5abd8aa59832d81afbdce7a8e7",
          "md5": "50836073606f20ec5219b72896caa53e"
        }
      ]
    }
  ]
}
