{
  "formatVersion": "1.1",
  "component": {
    "group": "ru.dreremin",
    "module": "logging-starter",
    "version": "1.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "logging-starter-1.8-SNAPSHOT.jar",
          "url": "logging-starter-1.8-SNAPSHOT.jar",
          "size": 22069,
          "sha512": "a0bb4056dd65fd76d5c2261ae4bece2675fd6c53586b52dd888a7d59538e8310896e623802aa69bc20b4b613de5e60f02263b0e208e4f568a2ce1b54041a9149",
          "sha256": "ee48fd77532a8f24bde0afc58103ae5253b0b76087a2d6d7bdc0d737c05307e6",
          "sha1": "3f6be0644bf0351e5e1a831615a8b24ef80e6757",
          "md5": "ecbdd69dfe64bc09263237305aed273b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "3.2.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "3.2.5"
          }
        },
        {
          "group": "org.springframework.cloud",
          "module": "spring-cloud-starter-openfeign",
          "version": {
            "requires": "4.1.4"
          }
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "logging-starter-1.8-SNAPSHOT.jar",
          "url": "logging-starter-1.8-SNAPSHOT.jar",
          "size": 22069,
          "sha512": "a0bb4056dd65fd76d5c2261ae4bece2675fd6c53586b52dd888a7d59538e8310896e623802aa69bc20b4b613de5e60f02263b0e208e4f568a2ce1b54041a9149",
          "sha256": "ee48fd77532a8f24bde0afc58103ae5253b0b76087a2d6d7bdc0d737c05307e6",
          "sha1": "3f6be0644bf0351e5e1a831615a8b24ef80e6757",
          "md5": "ecbdd69dfe64bc09263237305aed273b"
        }
      ]
    }
  ]
}
