{
  "formatVersion": "1.1",
  "component": {
    "group": "ru.dreremin",
    "module": "logging-starter",
    "version": "1.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "logging-starter-1.6-SNAPSHOT.jar",
          "url": "logging-starter-1.6-SNAPSHOT.jar",
          "size": 14946,
          "sha512": "3bf55a14a147a2720685073c8ce0427ce389444384adc47d9aab7a65eb7881106af53f46cec63a4ea1eb7311b5e04a5b2062fef08ba682cf30a0af8c2756a30c",
          "sha256": "e2d40845ef17e68b7774d3c79c18cb10a4532f1c3e0816af9526993922c1b3b8",
          "sha1": "3bb9c114a78e2d3d83afb9fad625532bc72018d7",
          "md5": "4d7971c83559eac76a674003c7d09de5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "3.2.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "3.2.5"
          }
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "logging-starter-1.6-SNAPSHOT.jar",
          "url": "logging-starter-1.6-SNAPSHOT.jar",
          "size": 14946,
          "sha512": "3bf55a14a147a2720685073c8ce0427ce389444384adc47d9aab7a65eb7881106af53f46cec63a4ea1eb7311b5e04a5b2062fef08ba682cf30a0af8c2756a30c",
          "sha256": "e2d40845ef17e68b7774d3c79c18cb10a4532f1c3e0816af9526993922c1b3b8",
          "sha1": "3bb9c114a78e2d3d83afb9fad625532bc72018d7",
          "md5": "4d7971c83559eac76a674003c7d09de5"
        }
      ]
    }
  ]
}
