{
  "formatVersion": "1.1",
  "component": {
    "group": "ru.dreremin",
    "module": "logging-starter",
    "version": "1.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "logging-starter-1.6-SNAPSHOT.jar",
          "url": "logging-starter-1.6-SNAPSHOT.jar",
          "size": 15124,
          "sha512": "a4be1004c146765bee8113ac974a4940d1b601ef23d20f2cfb015ce93fdd1caaa1234fc3ddc14ecd5e40beda2c17bd1b39729a37246150f691a4180bce9134dd",
          "sha256": "6c56ee5e778cac2113adf11f5a48572094d7b6b7d078c81ba011ef30372edb3b",
          "sha1": "67dd0273b07686a364f3d39ff9c9f7a49e03bd5b",
          "md5": "6870d669cca82ece024b27ecdc483c11"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "3.2.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "3.2.5"
          }
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "logging-starter-1.6-SNAPSHOT.jar",
          "url": "logging-starter-1.6-SNAPSHOT.jar",
          "size": 15124,
          "sha512": "a4be1004c146765bee8113ac974a4940d1b601ef23d20f2cfb015ce93fdd1caaa1234fc3ddc14ecd5e40beda2c17bd1b39729a37246150f691a4180bce9134dd",
          "sha256": "6c56ee5e778cac2113adf11f5a48572094d7b6b7d078c81ba011ef30372edb3b",
          "sha1": "67dd0273b07686a364f3d39ff9c9f7a49e03bd5b",
          "md5": "6870d669cca82ece024b27ecdc483c11"
        }
      ]
    }
  ]
}
